name: "Unit Test"
on:
  pull_request:
    branches:
      - main

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.x
      - name: "Unit Test"
        run: |
          dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
      - name: "Upload Code Coverage"
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          flags: unittests
          files: ./AliCloudDynamicDNS.Test/coverage.opencover.xml